language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

before_install: travis_retry composer self-update --preview
install: travis_retry composer install --no-interaction --prefer-dist --no-suggest --no-progress

script: vendor/bin/phpunit --coverage-text
