language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install: travis_retry composer self-update --preview
install: travis_retry composer install --no-interaction --prefer-dist --no-suggest --no-progress

script: vendor/bin/phpunit --coverage-text
